Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh"
  #config.vm.network :forwarded_port, guest:80, host:4567

  #config.vm.provision "chef_solo" do |chef|
    #chef.provisioning_path = "/tmp/vagrant-chef"
    #chef.add_recipe "java"
  #end

  #sync the vagrant folder for now so I can test chef code manually	
  config.vm.synced_folder ".", "/vagrant", disabled: false, type: 'rsync'
  config.vm.synced_folder "../leetcode", "/var/www/leetcode", type: 'rsync'
  config.gatling.rsync_on_startup = false 
end
